# Generated by Django 5.0.2 on 2024-02-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging_app", "0003_alter_message_has_been_read_alter_message_sender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="has_been_read",
            field=models.BooleanField(default=False),
        ),
    ]
